name: Docker Image Build and Push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Ruby 2.6
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./2.6/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: easyredir/ruby:2.6
        cache-from: type=registry,ref=user/app:latest
        cache-to: type=inline
    - name: Build and push Ruby 2.7
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./2.7/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: easyredir/ruby:2.7
        cache-from: type=registry,ref=user/app:latest
        cache-to: type=inline
    - name: Build and push Ruby 3.0
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./3.0/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: easyredir/ruby:3.0
        cache-from: type=registry,ref=user/app:latest
        cache-to: type=inline
    - name: Build and push Ruby 3.1
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./3.1/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: easyredir/ruby:3.1
        cache-from: type=registry,ref=user/app:latest
        cache-to: type=inline
